In [1]:
# importing the dataset

In [3]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/lekhyasri/jupyter-env/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/lekhyasri/jupyter-env/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
Downloading numpy-2.5.1-cp314-cp314-macosx_11_0_arm64.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 2.2 MB/s  0:00:05m0:00:0100:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.1 pandas-3.0.3

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [5]:
# cleaning the train dataset

In [6]:
# Fill Age with median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill Embarked with mode
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Drop Cabin column
df.drop("Cabin", axis=1, inplace=True)

In [7]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
# importing the test dataset to integrate

In [10]:
df_test = pd.read_csv("test.csv")

In [11]:
df_test["Fare"] = df_test["Fare"].fillna(df_test["Fare"].median())

In [12]:
test = pd.read_csv("test.csv")

In [13]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [14]:
# cleaning the test dataset before integrating it

In [15]:
# Fill Age with median
df_test["Age"] = df_test["Age"].fillna(df_test["Age"].median())

# Fill Fare with median (test.csv mein Fare missing hota hai)
df_test["Fare"] = df_test["Fare"].fillna(df_test["Fare"].median())

# Drop Cabin column
df_test.drop("Cabin", axis=1, inplace=True)

In [16]:
df_test.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [17]:
pip install numpy

Requirement already satisfied: numpy in /Users/lekhyasri/jupyter-env/lib/python3.14/site-packages (2.5.1)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [18]:
import numpy as np

df_test["Survived"] = np.nan

In [19]:
combined_df = pd.concat([df, df_test], ignore_index=True)

In [20]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   str
 4   Sex          1309 non-null   str
 5   Age          1309 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   str
 9   Fare         1309 non-null   float64
 10  Embarked     1309 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 112.6 KB

In [21]:
# now we are doing transformation

In [22]:
combined_df["Sex"] = combined_df["Sex"].map({"male": 0, "female": 1})

combined_df["Embarked"] = combined_df["Embarked"].map({"S": 0, "C": 1, "Q": 2})

In [23]:
# and now reduction

In [24]:
combined_df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)

In [25]:
combined_df.info()
combined_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    float64
 1   Pclass    1309 non-null   int64
 2   Sex       1309 non-null   int64
 3   Age       1309 non-null   float64
 4   SibSp     1309 non-null   int64
 5   Parch     1309 non-null   int64
 6   Fare      1309 non-null   float64
 7   Embarked  1309 non-null   int64
dtypes: float64(3), int64(5)
memory usage: 81.9 KB

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       0.0       3    0  22.0      1      0   7.2500         0
1       1.0       1    1  38.0      1      0  71.2833         1
2       1.0       3    1  26.0      0      0   7.9250         0
3       1.0       1    1  35.0      1      0  53.1000         0
4       0.0       3    0  35.0      0      0   8.0500         0